/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.project.app.kproducer;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.support.SendResult;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.util.concurrent.ListenableFuture;

/**
 *
 * @author armena
 */
@Service
@Component
@Slf4j
public class ProducerService {

    /**
     * The Kafka sender
     */
    private final KafkaSender kafkaSender;

    /**
     * Creates new engine input channel listener
     *
     * @param kafkaSender The Kafka sender
     */
    @Autowired
    public ProducerService(KafkaSender kafkaSender) {
        this.kafkaSender = kafkaSender;
    }

    public String sendMessage(String data) {

        ListenableFuture<SendResult<String, String>> sendGeneratedOutput = kafkaSender.sendData(json);
        boolean done = sendGeneratedOutput.isCancelled();
        if (done) {
            kafkaSender.sendErrors(data);
        }
        return sendGeneratedOutput.toString();
    }

    String json = "[\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e2825647b1d1e951a7\",\n"
            + "    \"index\": 0,\n"
            + "    \"guid\": \"3070d760-ebc6-4560-9315-b53ec2aadad0\",\n"
            + "    \"isActive\": false,\n"
            + "    \"balance\": \"$1,753.57\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 25,\n"
            + "    \"eyeColor\": \"green\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Kristi\",\n"
            + "      \"last\": \"Scott\"\n"
            + "    },\n"
            + "    \"company\": \"TELPOD\",\n"
            + "    \"email\": \"kristi.scott@telpod.me\",\n"
            + "    \"phone\": \"+1 (925) 428-2712\",\n"
            + "    \"address\": \"425 Hanover Place, Bangor, Georgia, 950\",\n"
            + "    \"about\": \"Reprehenderit labore laboris labore irure ullamco. Occaecat laboris ut non quis est nostrud aliquip occaecat ut id nostrud pariatur nostrud id. Ipsum ipsum mollit cupidatat exercitation deserunt ea proident. Aliqua adipisicing non adipisicing veniam est.\",\n"
            + "    \"registered\": \"Wednesday, February 8, 2017 5:03 PM\",\n"
            + "    \"latitude\": \"8.518003\",\n"
            + "    \"longitude\": \"-24.085271\",\n"
            + "    \"tags\": [\n"
            + "      \"dolore\",\n"
            + "      \"sit\",\n"
            + "      \"ullamco\",\n"
            + "      \"voluptate\",\n"
            + "      \"reprehenderit\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Berg Orr\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Blankenship Russell\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Angeline Mueller\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Kristi! You have 9 unread messages.\",\n"
            + "    \"favoriteFruit\": \"banana\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e214c707504228b40b\",\n"
            + "    \"index\": 1,\n"
            + "    \"guid\": \"027de88a-27b9-4dba-b247-419c2145b116\",\n"
            + "    \"isActive\": true,\n"
            + "    \"balance\": \"$1,682.19\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 37,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Melva\",\n"
            + "      \"last\": \"Steele\"\n"
            + "    },\n"
            + "    \"company\": \"DAYCORE\",\n"
            + "    \"email\": \"melva.steele@daycore.ca\",\n"
            + "    \"phone\": \"+1 (905) 504-2918\",\n"
            + "    \"address\": \"283 Fleet Place, Welch, Virgin Islands, 4669\",\n"
            + "    \"about\": \"Tempor ad non in duis quis pariatur incididunt. Consequat occaecat ad voluptate laboris sunt duis culpa ad non tempor exercitation dolor. Minim laboris tempor veniam anim commodo nostrud ad ad ex. Velit velit minim elit ex dolor cillum. Aute eiusmod amet et officia fugiat aliquip. Est excepteur mollit aliqua laborum consequat est exercitation aliqua tempor minim labore et dolor. Consequat ullamco sint nostrud laboris veniam incididunt irure laboris excepteur eiusmod ex ipsum.\",\n"
            + "    \"registered\": \"Friday, April 8, 2016 3:27 AM\",\n"
            + "    \"latitude\": \"14.164108\",\n"
            + "    \"longitude\": \"-8.99676\",\n"
            + "    \"tags\": [\n"
            + "      \"ad\",\n"
            + "      \"elit\",\n"
            + "      \"velit\",\n"
            + "      \"eu\",\n"
            + "      \"dolore\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Kay Stephens\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Patel Irwin\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Norris Lynn\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Melva! You have 10 unread messages.\",\n"
            + "    \"favoriteFruit\": \"apple\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e2f6cd0ffd7c2522dd\",\n"
            + "    \"index\": 2,\n"
            + "    \"guid\": \"cc96dba6-de12-42c2-8fd6-2b0180c5e8a3\",\n"
            + "    \"isActive\": true,\n"
            + "    \"balance\": \"$3,237.53\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 40,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Best\",\n"
            + "      \"last\": \"Barker\"\n"
            + "    },\n"
            + "    \"company\": \"COSMETEX\",\n"
            + "    \"email\": \"best.barker@cosmetex.biz\",\n"
            + "    \"phone\": \"+1 (942) 483-3952\",\n"
            + "    \"address\": \"805 Bijou Avenue, Newry, Mississippi, 566\",\n"
            + "    \"about\": \"Veniam ad veniam anim cupidatat quis aute culpa deserunt minim sint cupidatat. Anim mollit Lorem commodo tempor voluptate id sint cupidatat ad ullamco pariatur sit occaecat ad. Nostrud pariatur laboris ea magna excepteur tempor aliqua amet.\",\n"
            + "    \"registered\": \"Tuesday, March 19, 2019 7:51 AM\",\n"
            + "    \"latitude\": \"68.942449\",\n"
            + "    \"longitude\": \"-20.50922\",\n"
            + "    \"tags\": [\n"
            + "      \"qui\",\n"
            + "      \"eiusmod\",\n"
            + "      \"duis\",\n"
            + "      \"ad\",\n"
            + "      \"ad\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Deann Grimes\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Glass Atkins\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Petra May\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Best! You have 5 unread messages.\",\n"
            + "    \"favoriteFruit\": \"apple\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e271bac84760e9b3b3\",\n"
            + "    \"index\": 3,\n"
            + "    \"guid\": \"edce3fa3-9348-40c9-a20a-79bbaf1462b3\",\n"
            + "    \"isActive\": false,\n"
            + "    \"balance\": \"$2,998.99\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 23,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Kennedy\",\n"
            + "      \"last\": \"Moore\"\n"
            + "    },\n"
            + "    \"company\": \"MACRONAUT\",\n"
            + "    \"email\": \"kennedy.moore@macronaut.info\",\n"
            + "    \"phone\": \"+1 (858) 436-3498\",\n"
            + "    \"address\": \"954 Montgomery Place, Brantleyville, Arkansas, 1571\",\n"
            + "    \"about\": \"Voluptate ex do sunt Lorem dolor quis. Cillum ut pariatur ipsum velit occaecat ad incididunt adipisicing velit. Dolor Lorem minim occaecat nisi sit. Elit labore deserunt duis sit magna nisi consectetur. Enim pariatur qui tempor id laborum elit irure dolore commodo minim sunt aute laboris.\",\n"
            + "    \"registered\": \"Saturday, July 8, 2017 7:33 AM\",\n"
            + "    \"latitude\": \"20.993874\",\n"
            + "    \"longitude\": \"-58.882391\",\n"
            + "    \"tags\": [\n"
            + "      \"do\",\n"
            + "      \"deserunt\",\n"
            + "      \"nulla\",\n"
            + "      \"dolor\",\n"
            + "      \"incididunt\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Rosales Bishop\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Josie Acevedo\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Tisha Lyons\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Kennedy! You have 7 unread messages.\",\n"
            + "    \"favoriteFruit\": \"apple\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e2d57baa32fb704073\",\n"
            + "    \"index\": 4,\n"
            + "    \"guid\": \"92384a00-ecff-40ff-8020-c3eed0c3eaee\",\n"
            + "    \"isActive\": false,\n"
            + "    \"balance\": \"$1,582.49\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 33,\n"
            + "    \"eyeColor\": \"green\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Kirkland\",\n"
            + "      \"last\": \"Johns\"\n"
            + "    },\n"
            + "    \"company\": \"ROCKLOGIC\",\n"
            + "    \"email\": \"kirkland.johns@rocklogic.name\",\n"
            + "    \"phone\": \"+1 (905) 447-2156\",\n"
            + "    \"address\": \"627 Waldorf Court, Maury, Louisiana, 7216\",\n"
            + "    \"about\": \"Cillum commodo et consectetur minim officia eiusmod tempor. Labore ex nisi consequat nulla duis culpa magna ullamco veniam fugiat laborum enim minim. Voluptate fugiat excepteur fugiat culpa enim cillum magna et est aliquip aliqua qui veniam ea. Duis duis anim nostrud et laboris Lorem cillum reprehenderit officia esse eu adipisicing laborum ut. Irure labore non qui esse nisi cupidatat fugiat pariatur eiusmod elit fugiat non.\",\n"
            + "    \"registered\": \"Monday, March 18, 2019 3:38 PM\",\n"
            + "    \"latitude\": \"10.197559\",\n"
            + "    \"longitude\": \"92.621556\",\n"
            + "    \"tags\": [\n"
            + "      \"amet\",\n"
            + "      \"non\",\n"
            + "      \"enim\",\n"
            + "      \"ex\",\n"
            + "      \"ut\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Lela Odom\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Patrica Banks\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Blanca Collins\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Kirkland! You have 8 unread messages.\",\n"
            + "    \"favoriteFruit\": \"apple\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e22cf143a58945fa4b\",\n"
            + "    \"index\": 5,\n"
            + "    \"guid\": \"7c419e34-203f-4965-8ada-2b6ffd64a385\",\n"
            + "    \"isActive\": true,\n"
            + "    \"balance\": \"$2,210.89\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 28,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Minerva\",\n"
            + "      \"last\": \"Alexander\"\n"
            + "    },\n"
            + "    \"company\": \"ADORNICA\",\n"
            + "    \"email\": \"minerva.alexander@adornica.org\",\n"
            + "    \"phone\": \"+1 (889) 527-2795\",\n"
            + "    \"address\": \"656 Lawrence Avenue, Clarence, Alaska, 7292\",\n"
            + "    \"about\": \"Ut sit eiusmod mollit anim eu fugiat dolore occaecat sit enim cupidatat esse. Ullamco nisi eu incididunt do velit ullamco minim id magna id. Non do ea dolor in tempor reprehenderit dolor proident sint aliqua aliquip sunt. Laboris et sint culpa consequat ea nulla occaecat sit veniam proident. Aliquip consectetur nisi sint adipisicing velit nulla. Irure eu esse laborum amet pariatur consequat sunt.\",\n"
            + "    \"registered\": \"Sunday, July 30, 2017 5:03 PM\",\n"
            + "    \"latitude\": \"84.222376\",\n"
            + "    \"longitude\": \"115.050869\",\n"
            + "    \"tags\": [\n"
            + "      \"exercitation\",\n"
            + "      \"elit\",\n"
            + "      \"non\",\n"
            + "      \"aliqua\",\n"
            + "      \"proident\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Webster Lynch\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Rosario Booth\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Dee Cervantes\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Minerva! You have 7 unread messages.\",\n"
            + "    \"favoriteFruit\": \"strawberry\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e291824518f1034a52\",\n"
            + "    \"index\": 6,\n"
            + "    \"guid\": \"abdc60d9-0255-4340-8646-fd984254418f\",\n"
            + "    \"isActive\": false,\n"
            + "    \"balance\": \"$3,418.97\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 20,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Pruitt\",\n"
            + "      \"last\": \"Dickerson\"\n"
            + "    },\n"
            + "    \"company\": \"IPLAX\",\n"
            + "    \"email\": \"pruitt.dickerson@iplax.co.uk\",\n"
            + "    \"phone\": \"+1 (833) 428-3095\",\n"
            + "    \"address\": \"405 Conduit Boulevard, Glasgow, Colorado, 7790\",\n"
            + "    \"about\": \"Magna laboris ex commodo minim occaecat aute labore magna cillum cillum consequat. Amet magna deserunt nulla consectetur reprehenderit anim tempor labore exercitation amet enim eiusmod ex. Deserunt adipisicing non magna aliquip sint consequat. Elit culpa esse minim consequat aliqua ad et dolore ut sunt do veniam culpa esse.\",\n"
            + "    \"registered\": \"Tuesday, August 2, 2016 6:54 AM\",\n"
            + "    \"latitude\": \"42.209245\",\n"
            + "    \"longitude\": \"179.197988\",\n"
            + "    \"tags\": [\n"
            + "      \"ex\",\n"
            + "      \"consequat\",\n"
            + "      \"nostrud\",\n"
            + "      \"ullamco\",\n"
            + "      \"elit\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Gayle Cunningham\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Shelly Petty\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Leonard Collier\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Pruitt! You have 9 unread messages.\",\n"
            + "    \"favoriteFruit\": \"banana\"\n"
            + "  },\n"
            + "  {\n"
            + "    \"_id\": \"5cd415e280726f592d4c747d\",\n"
            + "    \"index\": 7,\n"
            + "    \"guid\": \"3394ed0b-9eb2-48de-8276-379f9b27f796\",\n"
            + "    \"isActive\": true,\n"
            + "    \"balance\": \"$2,634.56\",\n"
            + "    \"picture\": \"http://placehold.it/32x32\",\n"
            + "    \"age\": 27,\n"
            + "    \"eyeColor\": \"brown\",\n"
            + "    \"name\": {\n"
            + "      \"first\": \"Debra\",\n"
            + "      \"last\": \"Lee\"\n"
            + "    },\n"
            + "    \"company\": \"UNEEQ\",\n"
            + "    \"email\": \"debra.lee@uneeq.biz\",\n"
            + "    \"phone\": \"+1 (943) 592-2644\",\n"
            + "    \"address\": \"257 Bayard Street, Dennard, Alabama, 7519\",\n"
            + "    \"about\": \"Officia fugiat dolore eiusmod aliqua magna et proident. Adipisicing nulla irure duis aliqua anim velit commodo ipsum nostrud. Consequat enim ad sint labore elit nulla duis fugiat proident fugiat est proident. Enim est amet enim reprehenderit anim ad ad laborum ullamco voluptate do duis. Tempor ipsum exercitation consectetur non.\",\n"
            + "    \"registered\": \"Monday, January 28, 2019 1:22 PM\",\n"
            + "    \"latitude\": \"-72.754318\",\n"
            + "    \"longitude\": \"52.156498\",\n"
            + "    \"tags\": [\n"
            + "      \"velit\",\n"
            + "      \"reprehenderit\",\n"
            + "      \"sit\",\n"
            + "      \"elit\",\n"
            + "      \"ullamco\"\n"
            + "    ],\n"
            + "    \"range\": [\n"
            + "      0,\n"
            + "      1,\n"
            + "      2,\n"
            + "      3,\n"
            + "      4,\n"
            + "      5,\n"
            + "      6,\n"
            + "      7,\n"
            + "      8,\n"
            + "      9\n"
            + "    ],\n"
            + "    \"friends\": [\n"
            + "      {\n"
            + "        \"id\": 0,\n"
            + "        \"name\": \"Lester Small\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 1,\n"
            + "        \"name\": \"Camille Mccormick\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"id\": 2,\n"
            + "        \"name\": \"Riggs Pope\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"greeting\": \"Hello, Debra! You have 8 unread messages.\",\n"
            + "    \"favoriteFruit\": \"strawberry\"\n"
            + "  }\n"
            + "]";
}
