management:
  security:  
    enabled: false   
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'


server:
  port: 5000
  connection-timeout: 30000
  
spring:
  application:
    name: kadmin     

  kafka:   
    listener:
      ack-mode: MANUAL   
    consumer:
      bootstrap-servers: kafka:9092
      group-id: mpturbine     
      auto-offset-reset: earliest         
      enable-auto-commit: false
      session.timeout.ms: 100
      request.timeout.ms: 900000
      max.poll.interval.ms: 300000
      max.poll.records: 500    
      fetch-max-wait: 1000
      fetch-min-size: 1048576 
       
  