management:
  security:  
    enabled: false   
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'


server:
  port: 5002
  connection-timeout: 30000
  
spring:
  application:
    name: collector     

  kafka:
    listener:
      ack-mode: MANUAL
    producer:
      batch-size: 1048570000
      bootstrap-servers: kafka:9092
      buffer-memory: 97938193
      client-id: collector
      retries: 10   
    consumer:
      bootstrap-servers:  kafka:9092
      group-id: mpcollector     
      auto-offset-reset: earliest         
      enable-auto-commit: false
      session.timeout.ms: 300
      request.timeout.ms: 9000
      max.poll.interval.ms: 30000
      max.poll.records: 5000    
      fetch-max-wait: 1000
      fetch-min-size: 1048576
       
  